<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domain\Geo\Models\Country;
use App\Domain\Taxonomy\Models\Activity;
use App\Domain\Taxonomy\Models\ActivityNomenclature;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Nomenclature "NAM" (référencée par `CountrySeeder` pour le Maroc) : pas
 * une classification officielle comme la NAF française, mais une liste
 * dérivée du texte libre de `docs/MAROC_ENTREPRISE.xlsx` (colonne
 * "Catégories"). Les ~300 entrées ci-dessous sont les groupes les plus
 * fréquents après normalisation (voir `MoroccoCategoryNormalizer`) —
 * ~31 % des lignes du fichier, le reste étant trop fragmenté (texte libre
 * non structuré, cf. l'échange qui a produit ce fichier) pour être mappé
 * sans deviner. `code` est la clé de normalisation elle-même : le
 * transformer d'import recalcule cette même clé à partir de la catégorie
 * brute d'une ligne pour retrouver l'activité correspondante.
 */
class MoroccoActivitySeeder extends Seeder
{
    public function run(): void
    {
        $country = Country::query()->where('code', 'MA')->first();

        if ($country === null) {
            return;
        }

        $nomenclature = ActivityNomenclature::query()->updateOrCreate(
            ['code' => 'NAM'],
            ['name' => 'Catégories libres (Maroc, dérivées du scraping annuaire)', 'country_id' => $country->id],
        );

        foreach (self::entries() as $entry) {
            Activity::query()->updateOrCreate(
                ['nomenclature_id' => $nomenclature->id, 'code' => $entry['code']],
                [
                    'parent_id' => null,
                    'level' => 1,
                    'label' => $entry['label'],
                    'public_label' => $entry['label'],
                    'slug' => Str::slug($entry['label']),
                    'is_publishable' => true,
                ],
            );
        }
    }

    /** @return array<int, array{code: string, label: string}> */
    private static function entries(): array
    {
        return [
            ['code' => 'transport de marchandise', 'label' => 'Transport de marchandises'],
            ['code' => 'communication agencie', 'label' => 'Communication Agencies'],
            ['code' => 'promotion immobiliere', 'label' => 'Promotion immobiliere'],
            ['code' => 'transport touristique', 'label' => 'Transport touristique'],
            ['code' => 'import export', 'label' => 'Import export'],
            ['code' => 'travaux diver ou construction', 'label' => 'Travaux divers ou construction'],
            ['code' => 'travaux diver', 'label' => 'Travaux divers'],
            ['code' => 'location de voiture san chauffeur', 'label' => 'Location de voitures sans chauffeur'],
            ['code' => 'printing companie', 'label' => 'Printing Companies'],
            ['code' => 'agence voyage', 'label' => 'Agence de voyage'],
            ['code' => 'insurance broker', 'label' => 'Insurance Brokers'],
            ['code' => 'vocational training', 'label' => 'Vocational Training'],
            ['code' => 'promoteur a la construction d immeuble', 'label' => "Promoteur a la construction d'immeubles"],
            ['code' => 'concessionnaire de service telephonique', 'label' => 'Concessionnaire de services telephoniques'],
            ['code' => 'architect', 'label' => 'Architects'],
            ['code' => 'event management', 'label' => 'Event Management'],
            ['code' => 'computer engineering', 'label' => 'Computer Engineering'],
            ['code' => 'bank and financial institution', 'label' => 'Banks and Financial Institutions'],
            ['code' => 'centre d appel', 'label' => "Centre d'appel"],
            ['code' => 'digital printing', 'label' => 'Digital Printing'],
            ['code' => 'computer hardware', 'label' => 'Computer hardware'],
            ['code' => 'marchand effectuant import export', 'label' => 'Marchand effectuant import export'],
            ['code' => 'auto repair mechanical service', 'label' => 'Auto Repair & Mechanical Services'],
            ['code' => 'transport national et international de marchandise', 'label' => 'Transport national et international de marchandises'],
            ['code' => 'location de voiture', 'label' => 'Location de voitures'],
            ['code' => 'car rental', 'label' => 'Car rental'],
            ['code' => 'call center', 'label' => 'Call Centers'],
            ['code' => 'real estate developer', 'label' => 'Real Estate Developers'],
            ['code' => 'language school', 'label' => 'Language Schools'],
            ['code' => 'transport de personnel', 'label' => 'Transport de personnel'],
            ['code' => 'car wash', 'label' => 'Car Wash'],
            ['code' => 'transport routier de marchandise', 'label' => 'Transport routier de marchandises'],
            ['code' => 'construction', 'label' => 'Construction'],
            ['code' => 'dentiste cabinet dentaire', 'label' => 'Dentistes - Cabinets dentaires'],
            ['code' => 'travaux de construction', 'label' => 'Travaux de construction'],
            ['code' => 'graphic designer', 'label' => 'Graphic Designers'],
            ['code' => 'spare part', 'label' => 'Spare parts'],
            ['code' => 'promoteur immobilier', 'label' => 'Promoteur immobilier'],
            ['code' => 'md effectuant import export', 'label' => 'Md effectuant import-export'],
            ['code' => 'travaux diver de construction', 'label' => 'Travaux divers de construction'],
            ['code' => 'negociant', 'label' => 'Negociant'],
            ['code' => 'travaux diver ou de construction', 'label' => 'Entrepreneur de travaux divers ou de construction'],
            ['code' => 'bureau d etude', 'label' => "Tenant un bureau d'etudes"],
            ['code' => 'construction equipment', 'label' => 'Construction Equipment'],
            ['code' => 'translator interpreter', 'label' => 'Translators / Interpreters'],
            ['code' => 'travaux de comptabilite', 'label' => 'Entrepreneur de travaux de comptabilite'],
            ['code' => 'transport du personnel', 'label' => 'Transport du personnel'],
            ['code' => 'transport de marchandise national et international', 'label' => 'Transport de marchandises national et international'],
            ['code' => 'exploitation agricole', 'label' => 'Exploitation agricole'],
            ['code' => 'construction civil engineering', 'label' => 'Construction & Civil Engineering'],
            ['code' => 'transport national et international', 'label' => 'Transport national et international'],
            ['code' => 'pharmacie', 'label' => 'Pharmacies'],
            ['code' => 'transport de voyageur', 'label' => 'Transport de voyageurs'],
            ['code' => 'loueur de vehicule automobile san chauffeur', 'label' => 'Loueur de vehicules automobiles sans chauffeur'],
            ['code' => 'human resource management', 'label' => 'Human Resources Management'],
            ['code' => 'hardware store', 'label' => 'Hardware stores'],
            ['code' => 'transport', 'label' => 'Transport'],
            ['code' => 'gynecologist', 'label' => 'Gynecologist'],
            ['code' => 'transitaire', 'label' => 'Transitaire'],
            ['code' => 'loueur de vehicule automobile', 'label' => 'Loueur de vehicules automobiles'],
            ['code' => 'location de vehicule san chauffeur', 'label' => 'Location de vehicules sans chauffeur'],
            ['code' => 'construction et travaux diver', 'label' => 'Construction et travaux divers'],
            ['code' => 'internet service provider', 'label' => 'Internet service providers'],
            ['code' => 'telecommunication', 'label' => 'Telecommunication'],
            ['code' => 'conseil de gestion', 'label' => 'Conseil de gestion'],
            ['code' => 'internet cafe', 'label' => 'Internet Cafés'],
            ['code' => 'cooling air conditioning', 'label' => 'Cooling / Air Conditioning'],
            ['code' => 'import export negoce', 'label' => 'Import export negoce'],
            ['code' => 'negoce', 'label' => 'Negoce'],
            ['code' => 'publicite', 'label' => 'Entrepreneur de publicite'],
            ['code' => 'driving school', 'label' => 'Driving schools'],
            ['code' => 'location de vehicule automobile san chauffeur', 'label' => 'Location de vehicules automobiles sans chauffeur'],
            ['code' => 'import et export', 'label' => 'Import et export'],
            ['code' => 'construction material', 'label' => 'Construction Materials'],
            ['code' => 'transport de marchandise par automobile', 'label' => 'Entrepreneur de transport de marchandises par automobiles'],
            ['code' => 'la gestion d exploitation agricole', 'label' => "Entrepreneur de la gestion d'exploitation agricole"],
            ['code' => 'transit', 'label' => 'Transit'],
            ['code' => 'importation et exportation', 'label' => 'Importation et exportation'],
            ['code' => 'transport personnel', 'label' => 'Transport personnel'],
            ['code' => 'agence publicite', 'label' => 'Tenant une agence de publicite'],
            ['code' => 'agence communication', 'label' => 'Agence de communication'],
            ['code' => 'travaux diver et negoce', 'label' => 'Travaux divers et negoce'],
            ['code' => 'maison d hote', 'label' => "Maison d'hôte"],
            ['code' => 'sign and engraving', 'label' => 'Signs and Engraving'],
            ['code' => 'aviculture', 'label' => 'Aviculture'],
            ['code' => 'installation electrique', 'label' => "Entrepreneur d'installation electrique"],
            ['code' => 'toy and game store', 'label' => 'Toy and game stores'],
            ['code' => 'teleboutique', 'label' => 'Teleboutique'],
            ['code' => 'promotional item and corporate gift', 'label' => 'Promotional Items and Corporate Gifts'],
            ['code' => 'travaux diver et de construction', 'label' => 'Travaux divers et de construction'],
            ['code' => 'confection', 'label' => 'Confection'],
            ['code' => 'travaux diver et construction', 'label' => 'Travaux divers et construction'],
            ['code' => 'transport de marchandise import export', 'label' => 'Transport de marchandises import-export'],
            ['code' => 'wood joinery', 'label' => 'Wood Joinery'],
            ['code' => 'centre d appel telephonique', 'label' => "Centre d'appels telephoniques"],
            ['code' => 'travaux diver import export', 'label' => 'Travaux divers - import export'],
            ['code' => 'agence immobiliere', 'label' => 'Agence immobiliere'],
            ['code' => 'travaux de construction et travaux diver', 'label' => 'Travaux de construction et travaux divers'],
            ['code' => 'restauration', 'label' => 'Restauration'],
            ['code' => 'negoce import export', 'label' => 'Negoce import export'],
            ['code' => 'kitchen', 'label' => 'Kitchens'],
            ['code' => 'transporteur de marchandise', 'label' => 'Transporteur de marchandises'],
            ['code' => 'metal construction', 'label' => 'Metal Constructions'],
            ['code' => 'agence voyage et de tourisme', 'label' => 'Agence de voyages et de tourisme'],
            ['code' => 'car sale', 'label' => 'Car sales'],
            ['code' => 'courtier d assurance', 'label' => "Courtier d'assurances"],
            ['code' => 'travaux diver transport de marchandise', 'label' => '- travaux divers - transport de marchandises pour autrui'],
            ['code' => 'agriculture', 'label' => 'Agriculture'],
            ['code' => 'concessionnaire de service telephonique internet', 'label' => 'Concessionnaire de services telephoniques (internet)'],
            ['code' => 'aviculteur', 'label' => 'Aviculteur'],
            ['code' => 'transport de marchandise travaux diver', 'label' => 'Transport de marchandises - travaux divers'],
            ['code' => 'marchand importateur', 'label' => 'Marchand importateur'],
            ['code' => 'marchand de materiaux de construction', 'label' => 'Marchand de materiaux de construction'],
            ['code' => 'transport international de marchandise', 'label' => 'Transport international de marchandises'],
            ['code' => 'advertising', 'label' => 'Advertising'],
            ['code' => 'import export et negoce', 'label' => 'Import export et negoce'],
            ['code' => 'marchand effectuant importation et exportation', 'label' => 'Marchand effectuant importation et exportation'],
            ['code' => 'transport international', 'label' => 'Transport international'],
            ['code' => 'distribution en tournee et transport de marchandise', 'label' => 'Distribution en tournee et transport de marchandises'],
            ['code' => 'ingenieur conseil', 'label' => 'Ingenieur conseil'],
            ['code' => 'fabricant de vetement confectionne', 'label' => 'Fabricant de vetements confectionnes'],
            ['code' => 'travel agencie', 'label' => 'Travel Agencies'],
            ['code' => 'traiteur', 'label' => 'Traiteur'],
            ['code' => 'agent d assurance', 'label' => "Agent d'assurances"],
            ['code' => 'media', 'label' => 'Media'],
            ['code' => 'transport national et international routier de marchandise', 'label' => 'Transport national et international routier de marchandises'],
            ['code' => 'car bodywork', 'label' => 'Car Bodywork'],
            ['code' => 'promotion immobiliere et touristique', 'label' => 'Promotion immobiliere et touristique'],
            ['code' => 'gestion d exploitation agricole', 'label' => "Gestion d'exploitation agricole"],
            ['code' => 'transport de marchandise et travaux diver', 'label' => 'Transport de marchandises et travaux divers'],
            ['code' => 'illuminated sign', 'label' => 'Illuminated Signs'],
            ['code' => 'boilermaking metal fabrication', 'label' => 'Boilermaking / Metal Fabrication'],
            ['code' => 'transport routier national et international de marchandise', 'label' => 'Transport routier national et international de marchandises'],
            ['code' => 'marchand effectuant importation exportation', 'label' => 'Marchand effectuant importation exportation'],
            ['code' => 'paint manufacturing sale', 'label' => 'Paint: Manufacturing & Sales'],
            ['code' => 'transfert d argent', 'label' => "Transfert d'argent"],
            ['code' => 'service informatique', 'label' => 'Service informatique'],
            ['code' => 'location de vehicule automobile', 'label' => 'Location de vehicules automobiles'],
            ['code' => 'travaux de batiment', 'label' => 'Travaux de batiment'],
            ['code' => 'menuiserie', 'label' => 'Entrepreneur de menuiserie'],
            ['code' => 'batiment', 'label' => 'Entrepreneur de batiments'],
            ['code' => 'transport marchandise', 'label' => 'Transport marchandises'],
            ['code' => 'advertising media agencie', 'label' => 'Advertising Media Agencies'],
            ['code' => 'travaux diver ou construction negociant', 'label' => 'Travaux divers ou construction, negociant'],
            ['code' => 'network telecommunication', 'label' => 'Networks - Telecommunications'],
            ['code' => 'clinique polyclinique', 'label' => 'Cliniques - Polycliniques'],
            ['code' => 'sanitation pipeline', 'label' => 'Sanitation / Pipelines'],
            ['code' => 'change manuel', 'label' => 'Change manuel'],
            ['code' => 'vente de materiaux de construction', 'label' => 'Vente de materiaux de construction'],
            ['code' => 'travaux diver negociant', 'label' => 'Entrepreneur de travaux divers - négociant'],
            ['code' => 'currency exchange office', 'label' => 'Currency Exchange Offices'],
            ['code' => 'toute operation immobiliere', 'label' => 'Toutes operations immobilieres'],
            ['code' => 'travaux diver negoce', 'label' => 'Travaux divers, negoce'],
            ['code' => 'restaurant', 'label' => 'Restaurant'],
            ['code' => 'plumber', 'label' => 'Plumbers'],
            ['code' => 'travaux d electricite', 'label' => "Travaux d'electricite"],
            ['code' => 'pepiniere', 'label' => 'Pepiniere'],
            ['code' => 'transport de voyageur transport touristique', 'label' => 'Entrepreneur de transport de voyageurs (transport touristique)'],
            ['code' => 'elevator', 'label' => 'Elevators'],
            ['code' => 'transport de marchandise pour compte d autrui', 'label' => "Entrepreneur de transport de marchandises pour compte d'autrui"],
            ['code' => 'immeuble promoteur immobilier', 'label' => 'Immeubles, promoteur immobilier'],
            ['code' => 'import export en general', 'label' => 'Import export en general'],
            ['code' => 'automatic system gate automation', 'label' => 'Automatic Systems & Gate Automation'],
            ['code' => 'toute operation de transport de materiaux de construction', 'label' => 'Toute opération de transport de matériaux de construction'],
            ['code' => 'gardiennage', 'label' => 'Gardiennage'],
            ['code' => 'organisation de circuit touristique', 'label' => 'Organisation des circuits touristiques.'],
            ['code' => 'woodworking', 'label' => 'Woodworking'],
            ['code' => 'insurance provider', 'label' => 'Insurance providers'],
            ['code' => 'promotion immobilier', 'label' => 'Promotion immobilier'],
            ['code' => 'coating surface finishe', 'label' => 'Coatings & Surface Finishes'],
            ['code' => 'publisher', 'label' => 'Publishers'],
            ['code' => 'equipement medicaux', 'label' => 'Equipements médicaux'],
            ['code' => 'restaurateur a la carte', 'label' => 'Restaurateur a la carte'],
            ['code' => 'informatique', 'label' => 'Informatique'],
            ['code' => 'marketing digital marketing', 'label' => 'Marketing & Digital Marketing'],
            ['code' => 'cafe restaurant', 'label' => 'Cafe restaurant'],
            ['code' => 'commissionnaire de transport', 'label' => 'Commissionnaire de transport'],
            ['code' => 'import export et travaux diver', 'label' => 'Import export et travaux divers'],
            ['code' => 'exploitation de terre agricole', 'label' => 'Exploitation des terres agricoles'],
            ['code' => 'transport public de marchandise', 'label' => 'Transport publics de marchandises'],
            ['code' => 'exploitation de teleboutique', 'label' => 'Exploitation de teleboutique'],
            ['code' => 'construction metallique', 'label' => 'Construction metallique'],
            ['code' => 'it computer service', 'label' => 'IT & Computer Services'],
            ['code' => 'moving storage', 'label' => 'Moving & Storage'],
            ['code' => 'travaux diver ou construction entrepreneur de', 'label' => 'Travaux divers ou constructions (entrepreneur de).'],
            ['code' => 'audiovisual and video production', 'label' => 'Audiovisual and Video Production'],
            ['code' => 'civil engineering', 'label' => 'Civil Engineering'],
            ['code' => 'transport de voyageur par automobile', 'label' => 'Entrepreneur de transport de voyageurs par automobiles'],
            ['code' => 'transport national de marchandise', 'label' => 'Transport national de marchandises'],
            ['code' => 'import export travaux diver', 'label' => 'Import - export, travaux divers'],
            ['code' => 'communication', 'label' => 'Communication'],
            ['code' => 'salon de the', 'label' => 'Salon de the'],
            ['code' => 'exploitation de carriere', 'label' => 'Exploitation de carrieres'],
            ['code' => 'marble work', 'label' => 'Marble works'],
            ['code' => 'activite de centre d appel', 'label' => "Activités de centres d'appels"],
            ['code' => 'informatique et telecommunication', 'label' => 'Informatique et telecommunication'],
            ['code' => 'transport de marchandise pour le compte de tier', 'label' => 'Le transport des marchandises pour le compte des tiers'],
            ['code' => 'water supply system', 'label' => 'Water supply systems'],
            ['code' => 'confection import export', 'label' => 'Confection import export'],
            ['code' => 'transport de voyageur touristique', 'label' => 'Entrepreneur de transport de voyageurs (touristique)'],
            ['code' => 'auto ecole', 'label' => 'Auto ecole'],
            ['code' => 'concessionnaire service telephonique', 'label' => 'Concessionnaire service telephonique'],
            ['code' => 'marchand effectuant import export negociant', 'label' => 'Marchand effectuant import export, negociant'],
            ['code' => 'elevage de volaille', 'label' => 'Elevage de volailles'],
            ['code' => 'alimentation generale', 'label' => 'Alimentation generale'],
            ['code' => 'transport touristique national et international', 'label' => 'Transport touristique national et international'],
            ['code' => 'transport de marchandise et negoce', 'label' => 'Transport de marchandises et négoce'],
            ['code' => 'la gestion d exploitation commerciale maison d hote', 'label' => "Entrepreneur de la gestion d'exploitation commerciale (maison d'hotes)"],
            ['code' => 'transport routier national et international', 'label' => 'Transport routier national et international'],
            ['code' => 'prestation de service', 'label' => 'Prestation de service'],
            ['code' => 'newspaper pres magazine', 'label' => 'Newspapers, Press & Magazines'],
            ['code' => 'menuiserie aluminium', 'label' => 'Menuiserie aluminium'],
            ['code' => 'courtage d assurance', 'label' => "Courtage d'assurances"],
            ['code' => 'travaux public', 'label' => 'Travaux publics'],
            ['code' => 'importation exportation', 'label' => 'Importation exportation'],
            ['code' => 'cyber cafe', 'label' => 'Cyber cafe'],
            ['code' => 'agence conseil en communication', 'label' => 'Agence conseil en communication'],
            ['code' => 'assurance', 'label' => 'Assurances'],
            ['code' => 'promotion a la construction d immeuble', 'label' => "Promotion a la construction d'immeubles"],
            ['code' => 'television', 'label' => 'Television'],
            ['code' => 'nettoyage', 'label' => 'Entrepreneur de nettoyage'],
            ['code' => 'travaux diver et negociant', 'label' => 'Travaux divers et negociant'],
            ['code' => 'fiduciaire', 'label' => 'Fiduciaire'],
            ['code' => 'kinesitherapeute', 'label' => 'Kinesitherapeute'],
            ['code' => 'transport de marchandise negoce', 'label' => 'Transport de marchandises/negoce'],
            ['code' => 'exploitation agricole import export', 'label' => 'Exploitation agricole -import/export'],
            ['code' => 'radio station', 'label' => 'Radio Stations'],
            ['code' => 'batiment et travaux diver', 'label' => 'Batiment et travaux divers'],
            ['code' => 'travaux diver et transport de marchandise', 'label' => 'Travaux divers et transports de marchandises'],
            ['code' => 'exploitant centre d appel telephonique call center', 'label' => "Exploitant centre d'appels telephoniques (call center)"],
            ['code' => 'negociant import export', 'label' => 'Negociant import export'],
            ['code' => 'travaux de construction travaux diver', 'label' => 'Travaux de construction travaux divers'],
            ['code' => 'bureau d etude d enquete et de recherche', 'label' => "Tenant un bureau d'etudes d'enquetes et de recherches"],
            ['code' => 'automobile loueur de vehicule', 'label' => 'Automobiles, loueur de véhicules.'],
            ['code' => 'welder', 'label' => 'Welders'],
            ['code' => 'travaux de menuiserie', 'label' => 'Travaux de menuiserie'],
            ['code' => 'agence transport touristique', 'label' => 'Agence de transport touristique'],
            ['code' => 'exploitant un milk bar', 'label' => 'Exploitant un milk bar'],
            ['code' => 'securite', 'label' => 'Securite'],
            ['code' => 'lavage auto', 'label' => 'Lavage auto'],
            ['code' => 'confection a l export', 'label' => "Confection a l'export"],
            ['code' => 'geolocation gp tracking', 'label' => 'Geolocation & GPS tracking'],
            ['code' => 'agriculture et elevage', 'label' => 'Agriculture et elevage'],
            ['code' => 'importation et exportation marchand ou intermediaire effectuant', 'label' => 'Importation et exportation (marchand ou intermédiaire effectuant) .'],
            ['code' => 'concessionnaire de service telephonique cyber cafe', 'label' => 'Concessionnaire de service telephonique (cyber cafe)'],
            ['code' => 'screen printing', 'label' => 'Screen Printing'],
            ['code' => 'transport de marchandise au compte d autrui', 'label' => "Transport de marchandises au compte d'autrui"],
            ['code' => 'programmation conseil et autre activite informatique', 'label' => 'Programmation, conseil et autres activites informatiques'],
            ['code' => 'md effectuant importation et exportation', 'label' => 'Md effectuant importation et exportation'],
            ['code' => 'transport routier de marchandise national et international', 'label' => 'Transport routier de marchandises national et international'],
            ['code' => 'import export transport de marchandise', 'label' => 'Import export - transport de marchandises'],
            ['code' => 'travaux diver ou construction import export', 'label' => 'Travaux divers ou construction import export'],
            ['code' => 'exploitation du transport urbain', 'label' => 'Exploitation du transport urbain'],
            ['code' => 'transport touristique routier', 'label' => 'Transport touristique routier'],
            ['code' => 'production audiovisuelle', 'label' => 'Production audiovisuelle'],
            ['code' => 'trade show fair and festival', 'label' => 'Trade Shows, Fairs and Festivals'],
            ['code' => 'packaging packing', 'label' => 'Packaging & Packing'],
            ['code' => 'exploitant milk bar', 'label' => 'Exploitant milk bar'],
            ['code' => 'imprimerie', 'label' => 'Imprimerie'],
            ['code' => 'fabrication de chaussure', 'label' => 'Fabrication de chaussures'],
            ['code' => 'hotellerie', 'label' => '- hôtellerie'],
            ['code' => 'car and motorcycle dealership', 'label' => 'Car and motorcycle dealerships'],
            ['code' => 'marchand effectuant import et export', 'label' => 'Marchand effectuant import et export'],
            ['code' => 'gestion de valeur mobiliere', 'label' => 'Gestion de valeurs mobilieres'],
            ['code' => 'activite agricole', 'label' => 'Activité agricole'],
            ['code' => 'travaux diver ou de construction transport de marchandise', 'label' => 'Travaux divers ou de construction ; transport de marchandises'],
            ['code' => 'transport de marchandise et import export', 'label' => 'Transport de marchandises et import - export'],
            ['code' => 'negociant marchand effectuant import export', 'label' => 'Negociant marchand effectuant import export'],
            ['code' => 'service telephonique', 'label' => 'Services telephoniques'],
            ['code' => 'travaux tou corp d etat', 'label' => "Travaux tous corps d'etat"],
            ['code' => 'agence voyage et tourisme', 'label' => 'Agence de voyages et tourisme.'],
            ['code' => 'negociant md effectuant import export', 'label' => 'Negociant, md effectuant import-export'],
            ['code' => 'location de voiture et transport touristique', 'label' => 'Location de voitures et transports touristiques'],
            ['code' => 'concrete', 'label' => 'Concrete'],
            ['code' => 'web agencie', 'label' => 'Web Agencies'],
            ['code' => 'exploitant d entrepot frigorifique', 'label' => "Exploitant d'entrepot frigorifique"],
            ['code' => 'tile tiling material', 'label' => 'Tiles & Tiling Materials'],
            ['code' => 'transport routier', 'label' => 'Transport routier'],
            ['code' => 'publicite et communication', 'label' => 'Publicite et communication'],
            ['code' => 'travaux diver de batiment', 'label' => 'Travaux divers de batiment'],
            ['code' => 'exploitant de maison d hote ou riad', 'label' => "Exploitant de maison d'hote ou riad"],
            ['code' => 'transport de marchandise import et export', 'label' => 'Transport de marchandises, import et export'],
            ['code' => 'formation professionnelle', 'label' => 'Formation professionnelle'],
            ['code' => 'promoteur immobiliere', 'label' => 'Promoteur immobiliere'],
            ['code' => 'transport national et international import export', 'label' => 'Transport national et international import export'],
            ['code' => 'marchand de materiel informatique', 'label' => 'Marchand de materiel informatique'],
            ['code' => 'gardiennage de edifice public ou prive', 'label' => 'Entreprise de gardiennage des edifices publics ou prives'],
            ['code' => 'transport de marchandise national et international import export', 'label' => 'Transport de marchandises national et international import export'],
            ['code' => 'transport routier de fret et service de demenagement', 'label' => 'Transports routiers de fret et services de déménagements'],
            ['code' => 'courtier d immeuble', 'label' => "Courtier d'immeubles"],
            ['code' => 'transit transport', 'label' => 'Transit, transport'],
            ['code' => 'magasin d alimentation generale', 'label' => "Tenant un magasin d'alimentation generale"],
            ['code' => 'construction ou travaux diver', 'label' => 'Construction ou travaux divers'],
            ['code' => 'parapharmacie', 'label' => 'Parapharmacie'],
            ['code' => 'transport urbain', 'label' => 'Transport urbain'],
            ['code' => 'conseil en communication', 'label' => 'Conseil en communication'],
            ['code' => 'concessionnaire de sce telephonique', 'label' => 'Concessionnaire de sces telephoniques'],
            ['code' => 'import export negociant', 'label' => 'Import export negociant'],
            ['code' => 'transport national et international de marchandise import export', 'label' => 'Transport national et international de .marchandises .import-export'],
            ['code' => 'fabrication de vetement confectionne', 'label' => 'Fabrication de vetements confectionnes'],
        ];
    }
}
